### PR TITLE
feat: Make remote and namespace configurable for staging and production

### PR DESCRIPTION
**Pull request by msvticket**
Support for namespace given to jxboot-resources by jenkins-x-charts/jxboot-resources#20.

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]

**Comment by ccojocar** [comment]
@msvticket There seems to be an issue with `remoteCluster` value key which is missing.

```
error: generating values.yaml for tree from /tmp/**-helm-apply-220451389/env: failed to execute Secrets template: /tmp/**-helm-apply-220451389/env/**boot-resources/values.tmpl.yaml: template: values.tmpl.yaml:74:28: executing "values.tmpl.yaml" at <.Environments.staging.remoteCluster>: map has no entry for key "remoteCluster"
```
Please could you have a look? Thanks!

**Comment by msvticket** [comment]
> @msvticket There seems to be an issue with `remoteCluster` value key which is missing.

Fixed.

Looking further up in `values.tmpl.yaml` it seems like `.Requirements.cluster.namespace` is assumed to exist, but might be empty. So I'll accommodate for that as well.

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
