### PR TITLE
chore: disable vault URL discovery in the pipeline file

### PR DESCRIPTION
**Pull request by ccojocar**

### CODE REVIEW

**Comment by abayer** [comment]
This isn’t needed since https://github.com/jenkins-x/jx/pull/5760 merged, and isn’t relevant here anyway since you changed the `boot-local` pipeline in the first place. =)

**Comment by ccojocar** [comment]
Yeah, just committed quickly to check what's going on when that is set.

**Comment by ccojocar** [comment]
I quickly checked the domains they seems to be fine. Let's let the test to fail that I can investigate a bit more closely the state to understand what's causing the issue.

**Pull request merged**
