### PR TITLE
fix: Add support for GitPublic field in requirements

### PR DESCRIPTION
**Pull request by abayer**
Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

**Comment by abayer** [comment]
@ccojocar - assuming my most recent run fails again, could you take a look? I know that whatever's going wrong (seems to be certificate related, either an unknown authority issue or like `Get https://bdd-spring-1571073339-**-staging.boot5.bdd.jenkins-x.rocks: x509: certificate is valid for ingress.local, not bdd-spring-1571073339-**-staging.boot5.bdd.jenkins-x.rocks`) but I know it's unrelated to my change and have no idea what to do about it. =) Thanks!

**Comment by ccojocar** [comment]
@abayer Yeah, I'll look at it. I saw it also yesterday failing systematically. Something seems to be broken.

**Pull request merged**
