### PR TITLE
fix: Switch back to using public repos for now

### PR DESCRIPTION
**Pull request by abayer**
See https://github.com/jenkins-x/jx/pull/5511

Signed-off-by: Andrew Bayer <andrew.bayer@gmail.com>

### CODE REVIEW

**Review by ccojocar — APPROVED** [review]

**Comment by abayer** [comment]
I think this may fail until we have a promoted builder image with the `latest` tag with https://github.com/jenkins-x/jx/pull/5511 incorporated.

**Comment by abayer** [comment]
Argh, `bdd-vault` is still failing:
```
STEP: install-vault command: /bin/sh -c ** step boot vault in dir: systems/vault
error: failed to load vault ingress template file vault-ing.tmpl.yaml: failed to execute Ingress template: vault-ing.tmpl.yaml: template: vault-ing.tmpl.yaml:7:24: executing "vault-ing.tmpl.yaml" at <.Requirements.vault.name>: map has no entry for key "vault"
error: failed to interpret pipeline file jenkins-x.yml: failed to run '/bin/sh -c ** step boot vault' command in directory 'systems/vault', output: ''
ERROR: Error: Command failed  ** boot -b
error: exit status 1
```

**Comment by abayer** [comment]
Oh, right, version stream. Duh.

**Pull request closed without merging**
