### PR TITLE
feat: upgrade velero from deprecated chart to new vamware-tanzu offic…

### PR DESCRIPTION
**Pull request by patrickleet**
…ial chart

### CODE REVIEW

**Comment by patrickleet** [comment]
https://github.com/jenkins-x/jenkins-x-versions/pull/1010

**Comment by patrickleet** [comment]
depends on https://github.com/jenkins-x/jenkins-x-versions/pull/1010

**Comment by patrickleet** [comment]
Tried this on my cluster now that it is in the version stream.

The default backup schedule created is invalid, though it was pretty easy to get it working again.

It's also pretty easy to get volume snapshots configured via the chart so I'm thinking an update for that would be good though I've only tried for AWS so far.

**Comment by msvticket** [comment]
This is not used by the Jenkins X project anymore

**Pull request closed without merging**
