### PR TITLE
chore: remove content irrelevant to user when setting up initial jenkins-x-boot-config

### LINKED ISSUE #7157: Remove content irrelevant to user when setting up initial  jenkins-x-boot-config
When creating the _jenkins-x-boot-config_ for booting a cluster, we are forking https://github.com/jenkins-x/jenkins-x-boot-config. This repository contains content which is irrelevant to the function of the boot config for the newly created cluster. This is confusing to the user and clutters the repository. 

Content which should not be included:

- _bdd_ directory
- .pre-commit-config.yaml
- .secrets.baseline
- clearcluster.sh
- jenkins-x-bdd-*.yml
- jenkins-x-release.yml

_prowConfig_ can probably be deleted now as well (even in the upstream repo itself)

### PR DESCRIPTION
**Pull request by hervelemeur**
Fixes https://github.com/jenkins-x/jx/issues/7157

> prowConfig can probably be deleted now as well (even in the upstream repo itself)

I kept it as we may want to use prow instead of lighthouse, at least until lighthouse has all prow features.

### CODE REVIEW

**Comment by hferentschik** [comment]
@hervelemeur, thanks for the pull request. Unfortunately, it's not as easy as removing these files from the repo. These files are driving the pull requests builds/contexts if someone submits a pull request. They run end to end tests that the suggested boot config change won't break any of the tested Jenkins X workflows. So for this repo they are needed.

When someone runs `jx boot` on his machine we clone this repository and use it as seed for the user's boot config. At this stage, these files make no sense since they won't work for the user. So what I tried to imply in  jenkins-x/jx#7157 was that need to do something on the `jx` side to filter out these files. We already do something special with the OWNERS file, so that's the code area one would have to look at. Maybe we can have some "smart" mechanism which allows us to exclude some files at fork/clone time.

**Comment by hferentschik** [comment]
Here is where we handle the OWNERS file btw -  https://github.com/jenkins-x/jx/blob/a7eac7965293fb3195dae3bb6f7fe4caac7dbb64/pkg/cmd/step/verify/step_verify_preinstall.go#L692

**Comment by hferentschik** [comment]
I am going to close this PR since we cannot delete these files directly in this repo.

**Comment by hervelemeur** [comment]
@hferentschik no problem, I understood with @deanesmith comment and yours this wasn't as simple as this naive PR. Thanks for the detailled explainations.

**Comment by hervelemeur** [comment]
@hferentschik there should be a method like "cleanBddFiles" (or something like that) to add after the "writeOwnersFile" one (or somewhere in the `jx boot` procedure), that's what you mean?

**Comment by hferentschik** [comment]
> there should be a method like "cleanBddFiles" (or something like that) to add after the "writeOwnersFile" one (or somewhere in the jx boot procedure), that's what you mean?

yeah some sort of function is needed in `jx`, maybe not `cleanBddFiles` since they are not all BDD related. Most of them, but not all. Maybe `cleanRepo` or `filterRepo`. The question is not so much how this particular function is called, but how it works. The most simplistic way would be to hard code the files and directories to delete in `jx`, but that seems not very flexible. Maybe we need some special ignore file in this repo which lists the files and directories we need to exclude when we fork and prepare the new environment directory. Within `jx` we would be looking for this file, delete all matches and the file itself. At least that's my current thinking around that. Any better ideas?

**Pull request closed without merging**
