### PR TITLE
fix: use NLB for jxing in AWS

### LINKED ISSUE #5790: jx boot creates classic load balancer instead of network load balancer on AWS
### Summary 

The jx instance we had setup using `jx install` created an NLB for ingress, but the jx instance created using `jx boot` on EKS seems to use a classic load balancer.

### Steps to reproduce the behavior

1. create fork of https://github.com/jenkins-x/jenkins-x-boot-config in bitbucket cloud.
2. changes in jx-requirements.yml

```yml
cluster:
  provider: eks
  gitKind: bitbucketcloud
  gitName: bc
  gitServer: https://bitbucket.org
secretStorage: local
webhook: lighthouse
```
3. run `jx boot`

### Expected behavior

When setting up ingress, create a network load balancer just like `jx install` used to do

### Actual behavior

jx itself gets installed correctly, but it creates a classic load balancer

### Jx version

The output of `jx version` is:

```
NAME               VERSION
jx                 2.0.838
Kubernetes cluster v1.13.10-eks-5ac0f1
kubectl            v1.16.1
helm client        Client: v2.14.3+g0e7f3b6
git                2.21.0
Operating System   "Fedora release 30 (Thirty)"
```

### Jenkins type

- [x] Serverless Jenkins X Pipelines (Tekton + lighthouse)
- [ ] Classic Jenkins

### Kubernetes cluster

EKS cluster created using `eksctl` with config:

```yml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: <clusterName>
  region: ap-southeast-2

nodeGroups:
- name: spot-1
  minSize: 2
  maxSize: 10
  volumeSize: 50
  instancesDistribution:
    instanceTypes:
    - t3.2xlarge
    - t3a.2xlarge
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 0
    spotInstancePools: 2
  ssh:
    allow: true
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
      cloudWatch: true
- name: ondemand-1
  minSize: 0
  maxSize: 10
  volumeSize: 50
  instanceType: t3.2xlarge
  ssh:
    allow: true
  iam:
    withAddonPolicies:
      albIngress: true
      autoScaler: true
      cloudWatch: true
```

Install cluster autoscaler with [auto discovery](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#auto-discovery-setup)

### Operating system / Environment

Operating System   "Fedora release 30 (Thirty)"

### PR DESCRIPTION
**Pull request by gazal-k**
fix jenkins-x/jx#5790

### CODE REVIEW

**Comment by gazal-k** [comment]
This may not be the right way to solve this. Since the same chart has to be applied for other cloud providers.

Also, the chart icon references nginxinc/kubernetes-ingress. I was under the impression that Jenkins X uses kubernetes/ingress-nginx

**Comment by dgozalo** [comment]
Awesome, I tried this a few days ago and was about to do this exact same change.

One small change that I'd do is to put a go templates conditional on the provider, something like:

```
{{- if eq .Requirements.cluster.provider "eks" }}
   .....
 {{- end }}
```

**Comment by gazal-k** [comment]
If we put template conditional in there, should we rename the file to `values.tmpl.yaml` like what is done for https://github.com/jenkins-x/jenkins-x-boot-config/blob/master/systems/vault/values.tmpl.yaml ?

**Comment by gazal-k** [comment]
@dgozalo thank you. I've made the recommended change

**Review by ccojocar — APPROVED** [review]

**Pull request merged**
